update code passed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,7 +25,6 @@ jobs:
           - tests/test_redirect.py
 
 
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -47,11 +46,20 @@ jobs:
           pip3 install -r requirements.txt
           pip3 install allure-pytest
 
+      # - name: Run tests with pytest
+      #   run: |
+      #     pytest -v ${{ matrix.suite }} --alluredir=allure-results --maxfail=1 --disable-warnings -q | tee pytest-output.txt
+      #     echo "${PIPESTATUS[0]}" > exit-code.txt
+      #   continue-on-error: true
+
       - name: Run tests with pytest
+        id: pytest
+        continue-on-error: true  # Allow job to continue even if tests fail
         run: |
-          pytest -v ${{ matrix.suite }} --alluredir=allure-results --maxfail=1 --disable-warnings -q | tee pytest-output.txt
-          echo "${PIPESTATUS[0]}" > exit-code.txt
-        continue-on-error: true
+          pytest -v ${{ matrix.suite }} \
+            --alluredir=allure-results \
+            --disable-warnings \
+            -q
 
       - name: Set safe artifact name
         id: sanitize
